name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build-and-lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Print puppeteer Chromium path & version
        run: |
          echo "puppeteer path: $(node -e "console.log(require('puppeteer').executablePath())")"
          CHROME_PATH=$(node -e "console.log(require('puppeteer').executablePath())")
          $CHROME_PATH --version || true

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
